# Site settings
title: O que eu ia falar?
email: raio.frontendizador@gmail.com
description: >
  O que eu ia falar?
  Moda, culinária, livros, filmes, estilo de vida.
baseurl: ""
url: "http://oqueeuiafalar.github.io"
twitter_username: raiofront
github_username:  teles
author_name: Jota Teles
facebook_username: jota.teles

# ids for third party scripts
google_analytics_id: UA-68664870
disqus_shortname: jotateles

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
paginate: 4
paginate_path: "/pagina/:num/"
exclude:
  - 'bower_components/**/*'
  - 'node_modules/**/*'
  - 'README.md'
  - 'bower.json'
  - 'package.json'
  - 'Gruntfile.js'
  - 'Gulpfile.js'
  - 'tasks'
